Member is now used instead of user
duckweedstudios/natebot pull request #70
Opened 2023-06-23 01:23 UTC by zade0123

2023-06-23 02:00 UTC, coreybriscoe requested changes
Change a variable name for clarity and consistency

2023-06-23 02:00 UTC, coreybriscoe commented on buttons/muteButton.js
Nitpicking here but we should leave that variable called `target`. It makes it more clear that the member being referenced is the target of the interaction rather than the sender. You have it this way in all the other files so this would also keep it consistent with that naming scheme

2023-06-23 02:00 UTC, coreybriscoe commented on embeds/getEmbed.js
See other comment, change variable name from `member` back to `target` to match other files

2023-06-27 17:43 UTC, coreybriscoe commented
Also I'm branching off of this branch to do #63 and #82 so don't delete after merging

2023-06-30 19:53 UTC, zade0123 commented on buttons/muteButton.js
Fixed

2023-06-30 20:05 UTC, coreybriscoe approved these changes

2023-06-30 20:15 UTC, merged